import logging
import os
import re
import pytest
from junitparser import JUnitXml, TestSuite, TestCase
from _pytest.junitxml import LogXML
from junitparser import TestSuite
import xml.etree.ElementTree as ET

from qmetryupload import upload_test_results

REPORT_PATH = 'report.xml'
REPORTING_MARKERS = ['testcasekey', 'storykey']

def parse_report_xml(junitxml, item_classnames):
    tree = ET.parse(junitxml)
    root = tree.getroot()

    for testsuite in root.iter('testsuite'):
        suite_name = testsuite.get('name')
        
        # Check if the suite name matches any key in item_classnames
        if suite_name in item_classnames:
            value = item_classnames[suite_name]
            if all(marker in value for marker in REPORTING_MARKERS):
                # Filter out empty strings and combine keys with their values
                pattern = '|'.join(REPORTING_MARKERS)
                markers = re.split(f'({pattern})', value)
                markers = [f'{markers[i]}={markers[i+1].strip()}' for i in range(1, len(markers)-1, 2)]
                for marker in markers:
                    key, val = marker.split('==')
                    testsuite.set(key, val.strip('"'))
            else:
                key, val = value.split('=')
                testsuite.set(key, val.strip('"'))

    # Save the modified XML back to the file
    tree.write(junitxml, encoding='utf-8', xml_declaration=True)
        
def pytest_configure(config):
    # Register the custom XML reporter with the static path
    junitxml = getattr(config.option, 'xmlpath', None)
    config._xml = CustomJUnitXML(junitxml)
    config.pluginmanager.register(config._xml)

## The CustomJUnitXML class extends the LogXML class and overrides the pytest_sessionfinish method to split the consolidated XML report into individual test suites.
## The default Junit report generated by pytest is a consolidated report that contains all the test cases. The split_junit_report method 
## reads the consolidated report and splits it into individual test suites based on the test case class name. 
class CustomJUnitXML(LogXML):
    def __init__(self, logfile):
        if logfile is None:
            logfile = REPORT_PATH
        super().__init__(logfile, prefix='')
        self.logfile = logfile
        self.session = None

    def pytest_sessionstart(self, session):
        # Store the session object
        self.session = session

    def pytest_sessionfinish(self, session, exitstatus):
        # Perform post-processing directly after the test session
        self.split_junit_report(self.logfile, session)

    def split_junit_report(self, input_file, session):

        if input_file is None:
            return
        xml = JUnitXml.fromfile(input_file)
        suites = {}
    
        for suite in xml:
            for case in suite:
                if case.classname not in suites:
                    suites[case.classname] = TestSuite(name=case.classname)
                    
                # Create a TestCase for each test and add it to the suite
                new_case = TestCase(name=case.name, classname=case.classname, time=case.time)
                new_case.result = case.result
                suites[case.classname].add_testcase(new_case)
                suites[case.classname].time += case.time
    
        # Write all suites to a single file
        consolidated_xml = JUnitXml()
        for suite in suites.values():
            consolidated_xml.add_testsuite(suite)

        consolidated_xml.write(input_file)

    
@pytest.hookimpl(tryfirst=True)
def pytest_collection_modifyitems(items, session):
    item_classnames = {}
    # Extract marker information from each test item
    for item in items:
        marker_strings = []
        for marker in item.iter_markers():
            ## verify that the marker only has testcasekey
            if marker.name in REPORTING_MARKERS:
                if marker.args:
                    marker_string = f'{marker.name}="{marker.args[0]}"'
                else:
                    marker_string = f'{marker.name}=""'
                marker_strings.append(marker_string)

        markers_str = " ".join(marker_strings)
        
        ## split the information required to store the testsuite name and the markers
        node_parts = item.nodeid.split("::")
        file_path = os.path.splitext(node_parts[0])[0]  # Get the file path without the test case
        class_name = node_parts[1]  # Get the class name
        suite_name = f"{file_path}.{class_name}".replace(os.sep, '.')  # Combine and replace slashes with dots
        
        if (markers_str != '' or None):
            item_classnames[suite_name] = markers_str

    session.item_classnames = item_classnames

def pytest_sessionfinish(session,exitstatus):
    junitxml = getattr(session.config.option, 'xmlpath', None)
    if junitxml is None:
        junitxml = REPORT_PATH
   
    logging.info(f'Uploading test results to QMetry')
    if session.item_classnames:
        parse_report_xml(junitxml,session.item_classnames)
        upload_test_results(junitxml)